//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deveel.Math {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Deveel.Math.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid rounding mode.
        /// </summary>
        internal static string math00 {
            get {
                return ResourceManager.GetString("math00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a power of ten too big.
        /// </summary>
        internal static string math01 {
            get {
                return ResourceManager.GetString("math01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scale out of range..
        /// </summary>
        internal static string math02 {
            get {
                return ResourceManager.GetString("math02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Infinite or NaN.
        /// </summary>
        internal static string math03 {
            get {
                return ResourceManager.GetString("math03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Division by zero.
        /// </summary>
        internal static string math04 {
            get {
                return ResourceManager.GetString("math04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Non-terminating decimal expansion; no exact representable decimal result..
        /// </summary>
        internal static string math05 {
            get {
                return ResourceManager.GetString("math05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Division impossible.
        /// </summary>
        internal static string math06 {
            get {
                return ResourceManager.GetString("math06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid Operation.
        /// </summary>
        internal static string math07 {
            get {
                return ResourceManager.GetString("math07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rounding necessary.
        /// </summary>
        internal static string math08 {
            get {
                return ResourceManager.GetString("math08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Overflow.
        /// </summary>
        internal static string math09 {
            get {
                return ResourceManager.GetString("math09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Underflow.
        /// </summary>
        internal static string math0A {
            get {
                return ResourceManager.GetString("math0A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a null unscaled value.
        /// </summary>
        internal static string math0B {
            get {
                return ResourceManager.GetString("math0B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Digits &lt; 0.
        /// </summary>
        internal static string math0C {
            get {
                return ResourceManager.GetString("math0C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a null RoundingMode.
        /// </summary>
        internal static string math0D {
            get {
                return ResourceManager.GetString("math0D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bad string format.
        /// </summary>
        internal static string math0E {
            get {
                return ResourceManager.GetString("math0E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bad precision value.
        /// </summary>
        internal static string math0F {
            get {
                return ResourceManager.GetString("math0F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a null roundingMode.
        /// </summary>
        internal static string math10 {
            get {
                return ResourceManager.GetString("math10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Radix out of range.
        /// </summary>
        internal static string math11 {
            get {
                return ResourceManager.GetString("math11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zero length BigInteger.
        /// </summary>
        internal static string math12 {
            get {
                return ResourceManager.GetString("math12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid signum value.
        /// </summary>
        internal static string math13 {
            get {
                return ResourceManager.GetString("math13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a signum-magnitude mismatch.
        /// </summary>
        internal static string math14 {
            get {
                return ResourceManager.GetString("math14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Negative bit address.
        /// </summary>
        internal static string math15 {
            get {
                return ResourceManager.GetString("math15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Negative exponent.
        /// </summary>
        internal static string math16 {
            get {
                return ResourceManager.GetString("math16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BigInteger divide by zero.
        /// </summary>
        internal static string math17 {
            get {
                return ResourceManager.GetString("math17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BigInteger: modulus not positive.
        /// </summary>
        internal static string math18 {
            get {
                return ResourceManager.GetString("math18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BigInteger not invertible..
        /// </summary>
        internal static string math19 {
            get {
                return ResourceManager.GetString("math19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a start &lt; 0: {0}.
        /// </summary>
        internal static string math1A {
            get {
                return ResourceManager.GetString("math1A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a numBits must be non-negative.
        /// </summary>
        internal static string math1B {
            get {
                return ResourceManager.GetString("math1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bitLength &lt; 2.
        /// </summary>
        internal static string math1C {
            get {
                return ResourceManager.GetString("math1C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
